[package]
name = "dirsize"
version = "0.2.0"
authors = ["jlgerber <jlgerber@gmail.com>"]
edition = "2018"

[dependencies]
ignore = "0.4.16"
structopt = "0.3.20"
byte-unit = "4.0.9"
thiserror = "1.0.22"
pad = "0.1.6"
